version: "3.5"
services:
  cake5:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    environment:
      - SECURITY_SALT
      - MYSQL_URL=mysql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - cake5
  mysql:
    image: mysql:5.6.51
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cake5
    ports:
      - 3306:3306
    networks:
      - cake5
volumes:
  mysql_data:
networks:
  cake5:
    name: cake5
